# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='park',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\x04park\"n\n\x13StatusSpotsResponse\x12.\n\x05spots\x18\x01 \x03(\x0b\x32\x1f.park.StatusSpotsResponse.Spots\x1a\'\n\x05Spots\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nstatusSpot\x18\x02 \x01(\x05\"#\n\x12StatusSpotsRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1c\n\x0bStatusReply\x12\r\n\x05teste\x18\x01 \x01(\x05\"\x87\x02\n\x10\x61\x64\x64\x43\x61meraRequest\x12\r\n\x05\x63\x61mId\x18\x01 \x01(\t\x12\x0f\n\x07nameCam\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x10\n\x08typeFile\x18\x04 \x01(\t\x12\x0f\n\x07\x63\x61mType\x18\x05 \x01(\t\x12\x0e\n\x06urlCam\x18\x06 \x01(\t\x12+\n\x05spots\x18\x07 \x03(\x0b\x32\x1c.park.addCameraRequest.Spots\x1a\x65\n\x05Spots\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x31\n\x05\x63ords\x18\x02 \x03(\x0b\x32\".park.addCameraRequest.Spots.Cords\x1a\x1d\n\x05\x43ords\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\"\n\x0e\x61\x64\x64\x43\x61meraReply\x12\x10\n\x08response\x18\x01 \x01(\x08\x32\x8c\x01\n\x07Parking\x12;\n\taddCamera\x12\x16.park.addCameraRequest\x1a\x14.park.addCameraReply\"\x00\x12\x44\n\x0bReturnSpots\x12\x18.park.StatusSpotsRequest\x1a\x19.park.StatusSpotsResponse\"\x00\x62\x06proto3')
)




_STATUSSPOTSRESPONSE_SPOTS = _descriptor.Descriptor(
  name='Spots',
  full_name='park.StatusSpotsResponse.Spots',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='park.StatusSpotsResponse.Spots.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statusSpot', full_name='park.StatusSpotsResponse.Spots.statusSpot', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=129,
)

_STATUSSPOTSRESPONSE = _descriptor.Descriptor(
  name='StatusSpotsResponse',
  full_name='park.StatusSpotsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spots', full_name='park.StatusSpotsResponse.spots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STATUSSPOTSRESPONSE_SPOTS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=129,
)


_STATUSSPOTSREQUEST = _descriptor.Descriptor(
  name='StatusSpotsRequest',
  full_name='park.StatusSpotsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='park.StatusSpotsRequest.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=166,
)


_STATUSREPLY = _descriptor.Descriptor(
  name='StatusReply',
  full_name='park.StatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='teste', full_name='park.StatusReply.teste', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=196,
)


_ADDCAMERAREQUEST_SPOTS_CORDS = _descriptor.Descriptor(
  name='Cords',
  full_name='park.addCameraRequest.Spots.Cords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='park.addCameraRequest.Spots.Cords.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='park.addCameraRequest.Spots.Cords.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=462,
)

_ADDCAMERAREQUEST_SPOTS = _descriptor.Descriptor(
  name='Spots',
  full_name='park.addCameraRequest.Spots',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='park.addCameraRequest.Spots.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cords', full_name='park.addCameraRequest.Spots.cords', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ADDCAMERAREQUEST_SPOTS_CORDS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=462,
)

_ADDCAMERAREQUEST = _descriptor.Descriptor(
  name='addCameraRequest',
  full_name='park.addCameraRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camId', full_name='park.addCameraRequest.camId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nameCam', full_name='park.addCameraRequest.nameCam', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='park.addCameraRequest.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typeFile', full_name='park.addCameraRequest.typeFile', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camType', full_name='park.addCameraRequest.camType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='urlCam', full_name='park.addCameraRequest.urlCam', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spots', full_name='park.addCameraRequest.spots', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ADDCAMERAREQUEST_SPOTS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=462,
)


_ADDCAMERAREPLY = _descriptor.Descriptor(
  name='addCameraReply',
  full_name='park.addCameraReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='park.addCameraReply.response', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=498,
)

_STATUSSPOTSRESPONSE_SPOTS.containing_type = _STATUSSPOTSRESPONSE
_STATUSSPOTSRESPONSE.fields_by_name['spots'].message_type = _STATUSSPOTSRESPONSE_SPOTS
_ADDCAMERAREQUEST_SPOTS_CORDS.containing_type = _ADDCAMERAREQUEST_SPOTS
_ADDCAMERAREQUEST_SPOTS.fields_by_name['cords'].message_type = _ADDCAMERAREQUEST_SPOTS_CORDS
_ADDCAMERAREQUEST_SPOTS.containing_type = _ADDCAMERAREQUEST
_ADDCAMERAREQUEST.fields_by_name['spots'].message_type = _ADDCAMERAREQUEST_SPOTS
DESCRIPTOR.message_types_by_name['StatusSpotsResponse'] = _STATUSSPOTSRESPONSE
DESCRIPTOR.message_types_by_name['StatusSpotsRequest'] = _STATUSSPOTSREQUEST
DESCRIPTOR.message_types_by_name['StatusReply'] = _STATUSREPLY
DESCRIPTOR.message_types_by_name['addCameraRequest'] = _ADDCAMERAREQUEST
DESCRIPTOR.message_types_by_name['addCameraReply'] = _ADDCAMERAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusSpotsResponse = _reflection.GeneratedProtocolMessageType('StatusSpotsResponse', (_message.Message,), dict(

  Spots = _reflection.GeneratedProtocolMessageType('Spots', (_message.Message,), dict(
    DESCRIPTOR = _STATUSSPOTSRESPONSE_SPOTS,
    __module__ = 'api_pb2'
    # @@protoc_insertion_point(class_scope:park.StatusSpotsResponse.Spots)
    ))
  ,
  DESCRIPTOR = _STATUSSPOTSRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:park.StatusSpotsResponse)
  ))
_sym_db.RegisterMessage(StatusSpotsResponse)
_sym_db.RegisterMessage(StatusSpotsResponse.Spots)

StatusSpotsRequest = _reflection.GeneratedProtocolMessageType('StatusSpotsRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATUSSPOTSREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:park.StatusSpotsRequest)
  ))
_sym_db.RegisterMessage(StatusSpotsRequest)

StatusReply = _reflection.GeneratedProtocolMessageType('StatusReply', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREPLY,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:park.StatusReply)
  ))
_sym_db.RegisterMessage(StatusReply)

addCameraRequest = _reflection.GeneratedProtocolMessageType('addCameraRequest', (_message.Message,), dict(

  Spots = _reflection.GeneratedProtocolMessageType('Spots', (_message.Message,), dict(

    Cords = _reflection.GeneratedProtocolMessageType('Cords', (_message.Message,), dict(
      DESCRIPTOR = _ADDCAMERAREQUEST_SPOTS_CORDS,
      __module__ = 'api_pb2'
      # @@protoc_insertion_point(class_scope:park.addCameraRequest.Spots.Cords)
      ))
    ,
    DESCRIPTOR = _ADDCAMERAREQUEST_SPOTS,
    __module__ = 'api_pb2'
    # @@protoc_insertion_point(class_scope:park.addCameraRequest.Spots)
    ))
  ,
  DESCRIPTOR = _ADDCAMERAREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:park.addCameraRequest)
  ))
_sym_db.RegisterMessage(addCameraRequest)
_sym_db.RegisterMessage(addCameraRequest.Spots)
_sym_db.RegisterMessage(addCameraRequest.Spots.Cords)

addCameraReply = _reflection.GeneratedProtocolMessageType('addCameraReply', (_message.Message,), dict(
  DESCRIPTOR = _ADDCAMERAREPLY,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:park.addCameraReply)
  ))
_sym_db.RegisterMessage(addCameraReply)



_PARKING = _descriptor.ServiceDescriptor(
  name='Parking',
  full_name='park.Parking',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=501,
  serialized_end=641,
  methods=[
  _descriptor.MethodDescriptor(
    name='addCamera',
    full_name='park.Parking.addCamera',
    index=0,
    containing_service=None,
    input_type=_ADDCAMERAREQUEST,
    output_type=_ADDCAMERAREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReturnSpots',
    full_name='park.Parking.ReturnSpots',
    index=1,
    containing_service=None,
    input_type=_STATUSSPOTSREQUEST,
    output_type=_STATUSSPOTSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARKING)

DESCRIPTOR.services_by_name['Parking'] = _PARKING

# @@protoc_insertion_point(module_scope)
