# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import api_pb2 as api__pb2


class ParkingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LoadCamera = channel.unary_unary(
        '/park.Parking/LoadCamera',
        request_serializer=api__pb2.LoadCameraRequest.SerializeToString,
        response_deserializer=api__pb2.LoadCameraReply.FromString,
        )


class ParkingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LoadCamera(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ParkingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LoadCamera': grpc.unary_unary_rpc_method_handler(
          servicer.LoadCamera,
          request_deserializer=api__pb2.LoadCameraRequest.FromString,
          response_serializer=api__pb2.LoadCameraReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'park.Parking', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
