# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='park',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\x04park\"\xa4\x02\n\x11LoadCameraRequest\x12\x10\n\x08namePark\x18\x01 \x01(\t\x12\x0f\n\x07nameCam\x18\x02 \x01(\t\x12\x15\n\rdirectoryData\x18\x04 \x01(\t\x12\x0c\n\x04path\x18\x05 \x01(\t\x12\x10\n\x08typeFile\x18\x06 \x01(\t\x12\x0f\n\x07\x63\x61mType\x18\x07 \x01(\t\x12\x0e\n\x06urlCam\x18\x08 \x01(\t\x12,\n\x05spots\x18\t \x03(\x0b\x32\x1d.park.LoadCameraRequest.Spots\x1a\x66\n\x05Spots\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x32\n\x05\x63ords\x18\x02 \x03(\x0b\x32#.park.LoadCameraRequest.Spots.Cords\x1a\x1d\n\x05\x43ords\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"#\n\x0fLoadCameraReply\x12\x10\n\x08response\x18\x01 \x01(\x08\x32I\n\x07Parking\x12>\n\nLoadCamera\x12\x17.park.LoadCameraRequest\x1a\x15.park.LoadCameraReply\"\x00\x62\x06proto3')
)




_LOADCAMERAREQUEST_SPOTS_CORDS = _descriptor.Descriptor(
  name='Cords',
  full_name='park.LoadCameraRequest.Spots.Cords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='park.LoadCameraRequest.Spots.Cords.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='park.LoadCameraRequest.Spots.Cords.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=312,
)

_LOADCAMERAREQUEST_SPOTS = _descriptor.Descriptor(
  name='Spots',
  full_name='park.LoadCameraRequest.Spots',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='park.LoadCameraRequest.Spots.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cords', full_name='park.LoadCameraRequest.Spots.cords', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LOADCAMERAREQUEST_SPOTS_CORDS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=312,
)

_LOADCAMERAREQUEST = _descriptor.Descriptor(
  name='LoadCameraRequest',
  full_name='park.LoadCameraRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namePark', full_name='park.LoadCameraRequest.namePark', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nameCam', full_name='park.LoadCameraRequest.nameCam', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='directoryData', full_name='park.LoadCameraRequest.directoryData', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='park.LoadCameraRequest.path', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typeFile', full_name='park.LoadCameraRequest.typeFile', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camType', full_name='park.LoadCameraRequest.camType', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='urlCam', full_name='park.LoadCameraRequest.urlCam', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spots', full_name='park.LoadCameraRequest.spots', index=7,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LOADCAMERAREQUEST_SPOTS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=312,
)


_LOADCAMERAREPLY = _descriptor.Descriptor(
  name='LoadCameraReply',
  full_name='park.LoadCameraReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='park.LoadCameraReply.response', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=349,
)

_LOADCAMERAREQUEST_SPOTS_CORDS.containing_type = _LOADCAMERAREQUEST_SPOTS
_LOADCAMERAREQUEST_SPOTS.fields_by_name['cords'].message_type = _LOADCAMERAREQUEST_SPOTS_CORDS
_LOADCAMERAREQUEST_SPOTS.containing_type = _LOADCAMERAREQUEST
_LOADCAMERAREQUEST.fields_by_name['spots'].message_type = _LOADCAMERAREQUEST_SPOTS
DESCRIPTOR.message_types_by_name['LoadCameraRequest'] = _LOADCAMERAREQUEST
DESCRIPTOR.message_types_by_name['LoadCameraReply'] = _LOADCAMERAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoadCameraRequest = _reflection.GeneratedProtocolMessageType('LoadCameraRequest', (_message.Message,), dict(

  Spots = _reflection.GeneratedProtocolMessageType('Spots', (_message.Message,), dict(

    Cords = _reflection.GeneratedProtocolMessageType('Cords', (_message.Message,), dict(
      DESCRIPTOR = _LOADCAMERAREQUEST_SPOTS_CORDS,
      __module__ = 'api_pb2'
      # @@protoc_insertion_point(class_scope:park.LoadCameraRequest.Spots.Cords)
      ))
    ,
    DESCRIPTOR = _LOADCAMERAREQUEST_SPOTS,
    __module__ = 'api_pb2'
    # @@protoc_insertion_point(class_scope:park.LoadCameraRequest.Spots)
    ))
  ,
  DESCRIPTOR = _LOADCAMERAREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:park.LoadCameraRequest)
  ))
_sym_db.RegisterMessage(LoadCameraRequest)
_sym_db.RegisterMessage(LoadCameraRequest.Spots)
_sym_db.RegisterMessage(LoadCameraRequest.Spots.Cords)

LoadCameraReply = _reflection.GeneratedProtocolMessageType('LoadCameraReply', (_message.Message,), dict(
  DESCRIPTOR = _LOADCAMERAREPLY,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:park.LoadCameraReply)
  ))
_sym_db.RegisterMessage(LoadCameraReply)



_PARKING = _descriptor.ServiceDescriptor(
  name='Parking',
  full_name='park.Parking',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=351,
  serialized_end=424,
  methods=[
  _descriptor.MethodDescriptor(
    name='LoadCamera',
    full_name='park.Parking.LoadCamera',
    index=0,
    containing_service=None,
    input_type=_LOADCAMERAREQUEST,
    output_type=_LOADCAMERAREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARKING)

DESCRIPTOR.services_by_name['Parking'] = _PARKING

# @@protoc_insertion_point(module_scope)
