# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import api_pb2 as api__pb2


class ParkingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addCamera = channel.unary_unary(
        '/park.Parking/addCamera',
        request_serializer=api__pb2.addCameraRequest.SerializeToString,
        response_deserializer=api__pb2.addCameraReply.FromString,
        )
    self.ReturnSpots = channel.unary_unary(
        '/park.Parking/ReturnSpots',
        request_serializer=api__pb2.StatusSpotsRequest.SerializeToString,
        response_deserializer=api__pb2.StatusSpotsResponse.FromString,
        )


class ParkingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def addCamera(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReturnSpots(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ParkingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addCamera': grpc.unary_unary_rpc_method_handler(
          servicer.addCamera,
          request_deserializer=api__pb2.addCameraRequest.FromString,
          response_serializer=api__pb2.addCameraReply.SerializeToString,
      ),
      'ReturnSpots': grpc.unary_unary_rpc_method_handler(
          servicer.ReturnSpots,
          request_deserializer=api__pb2.StatusSpotsRequest.FromString,
          response_serializer=api__pb2.StatusSpotsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'park.Parking', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
